services:
    ltc_server:
        container_name: ltc-server
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        command: npm run start:prod
        ports:
            - "${APP_PORT}:3000"
        restart: unless-stopped
        labels:
            - io.portainer.accesscontrol.teams=LTC
        networks:
            - ltc-net

networks:
    ltc-net:
        driver: bridge
