services:
    ltc_server:
        container_name: ltc-server
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        command: sh -c "npm run start:prod"
        restart: always
        ports:
            - ${APP_PORT}:${APP_PORT}
        networks:
            - ltc-net
        labels:
            - io.portainer.accesscontrol.teams=LTC

networks:
    ltc-net:
        driver: bridge
