version: "3.9"

services:
    ltc_server:
        container_name: ltc-server
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        environment:
            - NODE_ENV=${NODE_ENV:-production}
        command: npm run start:prod
        ports:
            - "${APP_PORT}:${APP_PORT}"
        restart: unless-stopped
        labels:
            - io.portainer.accesscontrol.teams=LTC
        networks:
            - ltc-net

networks:
    ltc-net:
        driver: bridge
